# Generated by Django 3.2.8 on 2021-10-31 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='Text', max_length=1024),
        ),
    ]
