# Generated by Django 3.2.8 on 2021-11-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificuser',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
